# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Increment version code and name, and build the APK"
  lane :build_brand_a do
    gradle(
      task: "assembleRelease",
      properties: {
        "versionCode" => (Time.now.to_i / 1000).to_s,
        "versionName" => "1.0.#{Time.now.to_i / 100000}"
      }
    )
  end
end